name: py-cordex-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - matplotlib-base
  - numpy
  - pooch
  - regionmask
  - setuptools
  - xarray
  - cftime
  - netCDF4
  - cdo==1.9.9 # python-cdo fails with cdo2
  - python-cdo
# for testing
  - pytest
  - pytest-cov
  - pytest-env
